# Generated by Django 2.2.6 on 2019-10-12 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190124_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 17, 23, 19, 660758), verbose_name='date published'),
        ),
    ]
