# Generated by Django 2.2.6 on 2019-10-12 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191012_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_price', models.CharField(max_length=200)),
                ('property_land_area', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 4, 11, 15, 937223), verbose_name='date published'),
        ),
    ]
